## Hexaploid map example
require(mappoly)
load(file = "~/repos/MAPpoly/TB_objects_to_test.RData")
source("~/repos/MAPpoly/util_func.R")
map<-TB.map.phase.BT[[12]]
#plot(map)
s <- make_seq_mappoly(TB.trifida, map$maps[[1]]$seq.num[1:200])
counts <- get_cache_two_pts_from_web(m = s$m)
tpt<-est_pairwise_rf(input.seq = s,
                     count.cache = counts,
                     n.clusters = 16,
                     verbose=TRUE)
mat <- rf_list_to_matrix(tpt, n.clusters = 1, thresh.LOD.ph = 5, thresh.LOD.rf = 5, shared.alleles = TRUE) 
plot(mat)
require(RColorBrewer)
image(mat$ShP, col = brewer.pal(length(na.omit(unique(as.numeric(mat$ShP)))), "Set1"))
image(mat$ShQ, col = brewer.pal(length(na.omit(unique(as.numeric(mat$ShP)))), "Set1"))



blocks1<-find_marker_blocks(input.seq = s,
                           search.type = "rf",
                           cut.lim  =  10e-5, ### to cut the tree generated by cluster analysis
                           seq.limit = 1000,
                           ord.limit = 10,
                           reconstruct = FALSE,
                           extend.tail = 10,
                           n.clusters = 16,
                           ph.thres = 3,
                           rf.mat = mat,
                           tol = 1e-02,
                           tol.final = 1e-03,
                           error = NULL,
                           verbose = TRUE,
                           count.cache = counts,
                           sub.map.size.limit  = 2, ### for sequential map construction
                           block.size.lim = 2, ### minimum number of markers per block
                           ask = FALSE)
plot(blocks1)
blocks1.filt <- filter_marker_blocks(blocks1, rf.thres = 0.005, ph.thresh = 3)
plot(blocks1)
blocks2<-find_marker_blocks(input.seq = s,
                            search.type = "seq",
                            cut.lim  =  10e-5, ### to cut the tree generated by cluster analysis
                            seq.limit = 1000,
                            ord.limit = 10,
                            reconstruct = FALSE,
                            extend.tail = 10,
                            n.clusters = 16,
                            ph.thres = 3,
                            rf.mat = mat,
                            tol = 1e-02,
                            tol.final = 1e-03,
                            error = NULL,
                            verbose = TRUE,
                            count.cache = counts,
                            sub.map.size.limit  = 2, ### for sequential map construction
                            block.size.lim = 2, ### minimum number of markers per block
                            ask = FALSE)
plot(blocks2)
blocks2.filt <- filter_marker_blocks(blocks2, rf.thres = 0.005, ph.thresh = 3)
plot(blocks2.filt)
blocks3<-find_marker_blocks(input.seq = s,
                            search.type = "orig.ord",
                            cut.lim  =  10e-5, ### to cut the tree generated by cluster analysis
                            seq.limit = 1000,
                            ord.limit = 3,
                            reconstruct = FALSE,
                            extend.tail = 10,
                            n.clusters = 16,
                            ph.thres = 3,
                            rf.mat = mat,
                            tol = 1e-02,
                            tol.final = 1e-03,
                            error = NULL,
                            verbose = TRUE,
                            count.cache = counts,
                            sub.map.size.limit  = 2, ### for sequential map construction
                            block.size.lim = 3, ### minimum number of markers per block
                            ask = FALSE)
plot(blocks3)
blocks3.filt <- filter_marker_blocks(blocks3, rf.thres = 0.005, ph.thresh = 3)
plot(blocks3.filt)


