context("Groupping")
test_that("assemble linkage groups correctly", {
  x <- est_pairwise_rf(make_seq_mappoly(tetra.solcap, 1:50))
  M <- rf_list_to_matrix(x)
  gr<-group_mappoly(M, expected.groups = 12, verbose = FALSE, inter = FALSE)
  y<-plot(gr)
  expect_is(gr, "mappoly.group")
  expect_null(y, NULL)
  expect_equal(round(mean(gr$groups.snp), 6), 4.32)
})
