# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
.vcf_stats_gz <- function(x, nrows = -1L, skip = 0L, verbose = 1L) {
    .Call('_mappoly_vcf_stats_gz', PACKAGE = 'mappoly', x, nrows, skip, verbose)
}

#' @export
.read_meta_gz <- function(x, stats, verbose) {
    .Call('_mappoly_read_meta_gz', PACKAGE = 'mappoly', x, stats, verbose)
}

#' @export
.read_body_gz <- function(x, stats, nrows = -1L, skip = 0L, cols = 0L, convertNA = 1L, verbose = 1L) {
    .Call('_mappoly_read_body_gz', PACKAGE = 'mappoly', x, stats, nrows, skip, cols, convertNA, verbose)
}

