# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_rf_estimation_disc_rcpp <- function(mrk_pairs_R, m_R, geno_R, dP_R, dQ_R, count_vector_R, count_matrix_phases_R, count_matrix_rownames_R, count_matrix_number_R, count_matrix_pos_R, count_matrix_length_R, tol_R, threads_R) {
    .Call('_mappoly_pairwise_rf_estimation_disc_rcpp', PACKAGE = 'mappoly', mrk_pairs_R, m_R, geno_R, dP_R, dQ_R, count_vector_R, count_matrix_phases_R, count_matrix_rownames_R, count_matrix_number_R, count_matrix_pos_R, count_matrix_length_R, tol_R, threads_R)
}

#' @export
.vcf_get_probabilities <- function(mat, pl_pos) {
    .Call('_mappoly_vcf_get_probabilities', PACKAGE = 'mappoly', mat, pl_pos)
}

#' @export
.vcf_transform_dosage <- function(mat, gt_pos) {
    .Call('_mappoly_vcf_transform_dosage', PACKAGE = 'mappoly', mat, gt_pos)
}

#' @export
.vcf_get_ploidy <- function(mat, gt_pos) {
    .Call('_mappoly_vcf_get_ploidy', PACKAGE = 'mappoly', mat, gt_pos)
}

#' @export
.vcf_get_depth <- function(mat, dp_pos) {
    .Call('_mappoly_vcf_get_depth', PACKAGE = 'mappoly', mat, dp_pos)
}

